# Generated by Django 4.2.7 on 2026-02-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'بخش', 'verbose_name_plural': 'بخش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'دستگاه', 'verbose_name_plural': 'دستگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='devicecycle',
            options={'ordering': ['-start_time'], 'verbose_name': 'سیکل', 'verbose_name_plural': 'سیکل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-date'], 'verbose_name': 'لاگ سرویس', 'verbose_name_plural': 'لاگ\u200cهای سرویس'},
        ),
        migrations.AlterField(
            model_name='department',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='device',
            name='baud_rate',
            field=models.IntegerField(default=9600, verbose_name='Baud Rate'),
        ),
        migrations.AlterField(
            model_name='device',
            name='capacity_kg',
            field=models.FloatField(default=10, verbose_name='ظرفیت (kg)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='chamber_volume_liter',
            field=models.FloatField(blank=True, null=True, verbose_name='حجم محفظه (L)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_type',
            field=models.CharField(choices=[('sim', 'شبیه\u200cساز (تست)'), ('rtu', 'Modbus RTU — RS485'), ('tcp', 'Modbus TCP — Ethernet')], default='sim', max_length=10, verbose_name='نوع اتصال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('autoclave', 'اتوکلاو'), ('incinerator', 'زباله\u200cسوز')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='installed_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ نصب'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین اتصال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='device',
            name='modbus_slave_id',
            field=models.IntegerField(default=1, verbose_name='Slave ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='MQTT Topic'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='سرویس بعدی'),
        ),
        migrations.AlterField(
            model_name='device',
            name='plc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP پی\u200cال\u200cسی'),
        ),
        migrations.AlterField(
            model_name='device',
            name='plc_port',
            field=models.IntegerField(default=502, verbose_name='پورت Modbus TCP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='polling_interval',
            field=models.IntegerField(default=5, verbose_name='فاصله polling (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='power_kw',
            field=models.FloatField(default=15, verbose_name='توان (kW)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='سریال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_port',
            field=models.CharField(default='/dev/ttyUSB0', max_length=50, verbose_name='پورت سریال (RS485)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'آنلاین'), ('offline', 'آفلاین'), ('error', 'خطا'), ('maintenance', 'در سرویس')], default='offline', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='device',
            name='steam_pressure_bar',
            field=models.FloatField(blank=True, null=True, verbose_name='فشار بخار (bar)'),
        ),
        migrations.AlterField(
            model_name='devicecycle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
