# Generated by Django 4.2.7 on 2026-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='monitoring__device__2f9b5e_idx',
            old_name='monitoring_device_ts_idx',
        ),
        migrations.AlterField(
            model_name='devicealert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
